apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sofka-web
  template:
    metadata:
      labels:
        app: sofka-web
    spec:
      containers:
        - name: sofka-web
          image: ldflores/sofka-inventory
          ports:
            - containerPort: 8081
          env:
            - name: inventory.server.port
              valueFrom:
                configMapKeyRef:
                  name: web-config
                  key: inventory.server.port
            - name: rabbit.uri
              valueFrom:
                configMapKeyRef:
                  name: web-config
                  key: rabbit.uri
            - name: inventory.mongo.uri
              valueFrom:
                configMapKeyRef:
                  name: web-config
                  key: inventory.mongo.uri

---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: NodePort
  selector:
    app: sofka-web
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30000